name: Crystal Marketing Solutions
favicon: null
layout_spectrum: 0.41971059888601303
typography_spectrum: 0.4830998408142477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6802051065023988
  lightness: 0.26557122776284814
  saturation: 0.8399829589761794
  rhythmicContrast: 0.04830672382377088
purpose: []
